app/routes.py
import os
from flask import send_file, Blueprint, request, redirect, url_for, render_template, flash, current_app, session, jsonify
from werkzeug.utils import secure_filename
import pandas as pd
from io import BytesIO
from app import db
from app.models import Table, AdminUser, Position, Status, Reservation
from datetime import datetime, time
from sqlalchemy import and_, or_
import pytz

main_bp = Blueprint('main', __name__)

# Функция для проверки, что файл имеет допустимое расширение
def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in current_app.config['ALLOWED_EXTENSIONS']

# Отображение списка столов
@main_bp.route('/tables', methods=['GET'])
def list_tables():
    tables = Table.query.order_by(Table.name).all()
    return render_template('tables_list.html', tables=tables)

# Редактирование информации о столе
@main_bp.route('/edit_table/<int:table_id>', methods=['GET', 'POST'])
def edit_table(table_id):
    table = Table.query.get_or_404(table_id)

    # Обработка формы редактирования
    if request.method == 'POST':
        table.name = request.form['name']
        table.description = request.form['description']
        table.capacity = request.form['capacity']
        table.deposit = request.form.get('deposit', type=float)

        # Обработка загрузки фото для стола
        file = request.files.get('photo')
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            new_photo_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
            file.save(new_photo_path)

            # Удаление старого фото, если оно существует
            if table.photo and os.path.exists(table.photo):
                os.remove(table.photo)

            table.photo = new_photo_path

        db.session.commit()
        flash('Стол успешно обновлён!', 'success')
        return redirect(url_for('main.list_tables')) # Перенаправление на список столов

    return render_template('edit_table.html', table=table) # Отображение формы редактирования

# Добавление нового стола
@main_bp.route('/add_table', methods=['GET', 'POST'])
def add_table():
    if request.method == 'POST':
        name = request.form['name']
        description = request.form.get('description')
        capacity = request.form['capacity']
        deposit = request.form.get('deposit', type=float)

        # Загрузка фотографии стола
        photo_path = None
        file = request.files.get('photo')
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            photo_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
            file.save(photo_path)

        # Создание нового стола
        new_table = Table(name=name, description=description, capacity=capacity, deposit=deposit, photo=photo_path)
        db.session.add(new_table)
        db.session.commit()

        flash('Новый стол успешно добавлен!', 'success')
        return redirect(url_for('main.list_tables'))

    return render_template('add_table.html')


# Админская панель
@main_bp.route('/brewmaster-secret/panel/')
def admin_panel():
    admin_id = session.get('admin_user_id') # Получаем ID администратора из сессии
    if not admin_id:
        flash('Пожалуйста, войдите в систему', 'warning')
        return redirect(url_for('auth.login')) # Перенаправление на страницу логина

    user = AdminUser.query.get(admin_id) # Получаем пользователя по ID
    if not user:
        session.pop('admin_user_id', None)  # Удаляем сессию, если пользователя нет
        flash('Ваша учётная запись была удалена. Войдите снова.', 'warning')
        return redirect(url_for('auth.login'))


    # Проверка роли пользователя (если это не админ, перенаправляем)
    if user.position_id == 2:
        return redirect(url_for('main.reservations'))

    return render_template('panel.html')

# Страница с сотрудниками
@main_bp.route('/brewmaster-secret/staff/')
def admin_staff():
    admin_id = session.get('admin_user_id') # Проверка сессии администратора
    if not admin_id:
        flash('Пожалуйста, войдите в систему', 'warning')
        return redirect(url_for('auth.login'))

    user = AdminUser.query.get(admin_id) # Получение информации о текущем пользователе
    if not user:
        session.pop('admin_user_id', None)
        flash('Ваша учётная запись была удалена. Войдите снова.', 'warning')
        return redirect(url_for('auth.login'))

    # Если это не админ, перенаправляем
    if user.position_id == 2:
        return redirect(url_for('main.reservations'))

    staff_users = AdminUser.query.all()
    positions = Position.query.all()
    return render_template('staff.html', staff_users=staff_users, positions=positions) # Отображение страницы сотрудников

# Страница бронирований
@main_bp.route('/brewmaster-secret/reservations/')
def reservations():
    admin_id = session.get('admin_user_id')
    if not admin_id:
        flash('Пожалуйста, войдите в систему', 'warning')
        return redirect(url_for('auth.login'))

    user = AdminUser.query.get(admin_id)
    if not user:
        session.pop('admin_user_id', None)
        flash('Ваша учётная запись была удалена. Войдите снова.', 'warning')
        return redirect(url_for('auth.login'))

    reservations = Reservation.query.order_by(Reservation.date.asc(), Reservation.start_time.asc()).all()
    return render_template('reservations.html', reservations=reservations)  # Отображение бронирований

@main_bp.route('/brewmaster-secret/reservations/filter')
def filter_reservations():
    admin_id = session.get('admin_user_id')
    if not admin_id:
        return jsonify({'error': 'Unauthorized'}), 401

    date = request.args.get('filter_date') # Дата фильтрации
    start_time = request.args.get('start_time') # Время начала
    end_time = request.args.get('end_time') # Время конца
    search_query = request.args.get('search_query') # Строка поиска

    query = Reservation.query.join(Table) # Начинаем запрос на бронирования и столы

    if date:
        try:
            date_obj = datetime.strptime(date, "%Y-%m-%d").date()
            query = query.filter(Reservation.date == date_obj)
        except ValueError:
            pass # Если дата некорректна, пропускаем

    if start_time:
        try:
            start_time_obj = datetime.strptime(start_time, "%H:%M").time()
            query = query.filter(Reservation.start_time >= start_time_obj)
        except ValueError:
            pass

    if end_time:
        try:
            end_time_obj = datetime.strptime(end_time, "%H:%M").time()
            query = query.filter(Reservation.end_time <= end_time_obj)
        except ValueError:
            pass

    if search_query:
        search = f"%{search_query.strip().lower()}%"
        query = query.filter(
            db.or_(
                db.func.lower(Reservation.name).like(search),
                db.func.lower(Reservation.special_requests).like(search),
                db.func.lower(Table.name).like(search)
            )
        )

    reservations = query.order_by(Reservation.date.asc(), Reservation.start_time.asc()).all() # Получаем результаты с фильтрами

    # Формируем и возвращаем результат в формате JSON
    return jsonify([
        {
            'id': r.id,
            'name': r.name,
            'status': r.status.name,
            'date': r.date.strftime('%d.%m.%Y'),
            'start_time': r.start_time.strftime('%H:%M'),
            'end_time': r.end_time.strftime('%H:%M'),
            'num_people': r.num_people,
            'table_name': r.table.name
        }
        for r in reservations
    ])

# Роут для добавления нового бронирования с админки
@main_bp.route('/brewmaster-secret/reservations/add', methods=['POST'])
def add_reservations():
    admin_id = session.get('admin_user_id')
    if not admin_id:
        flash('Пожалуйста, войдите в систему', 'warning')
        return redirect(url_for('auth.login'))

    # Получаем данные из формы
    name = request.form.get('name')
    date = request.form.get('date')
    start_time = request.form.get('time_from')
    end_time = request.form.get('time_to')
    num_people = request.form.get('people_count')
    phone = request.form.get('phone')
    email = request.form.get('email')
    special_requests = request.form.get('notes')

    # Обрабатываем дату и время
    try:
        date = datetime.strptime(date, "%Y-%m-%d") 
    except ValueError:
        flash('Неверный формат даты', 'error')
        return redirect(url_for('main.reservations'))

    try:
        start_time = datetime.strptime(start_time, "%H:%M").time()
        end_time = datetime.strptime(end_time, "%H:%M").time()
        table_name = request.form.get('table')
    except ValueError:
        flash('Неверный формат данных', 'error')
        return redirect(url_for('main.reservations'))

    # Проверяем, существует ли выбранный стол
    table = Table.query.filter_by(name=table_name).first()  # Исправление: ищем стол по имени
    if not table:
        flash('Указанный стол не существует', 'error')
        return redirect(url_for('main.reservations'))

    # Проверяем, существует ли конфликтующее бронирование для выбранного стола
    conflicting_reservation = Reservation.query.filter(
        Reservation.table_id == table.id,
        Reservation.date == date,  # Используем дату, полученную из формы
        or_(
            # Проверяем, если время начала новой брони перекрывает старую
            (Reservation.start_time <= start_time) & (Reservation.end_time > start_time),

            # Проверяем, если время конца новой брони перекрывает старую
            (Reservation.start_time < end_time) & (Reservation.end_time >= end_time)
        )
    ).first()

    if conflicting_reservation:
        flash('На этот стол уже существует бронирование в выбранное время', 'error')
        return redirect(url_for('main.reservations'))

    # Создаем объект бронирования и добавляем его в базу данных

app/templates/add_table.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Добавить стол</title>
    <style>
        body { font-family: Arial; padding: 20px; }
        label { display: block; margin-top: 10px; }
        input, textarea { width: 100%; padding: 6px; }
        button { margin-top: 15px; padding: 10px 20px; }
    </style>
</head>
<body>
    <h1>Добавить новый стол</h1>
    <form method="POST" enctype="multipart/form-data">
        <label for="name">Название:</label>
        <input type="text" name="name" required><br>
    
        <label for="description">Описание:</label>
        <textarea name="description"></textarea><br>
    
        <label for="capacity">Вместимость:</label>
        <input type="number" name="capacity" min="1" required><br>
    
        <label for="deposit">Депозит:</label>
        <input type="number" step="0.01" name="deposit"><br>
    
        <label for="photo">Загрузить фотографию:</label>
        <input type="file" name="photo"><br>
    
        <button type="submit">Добавить стол</button>
    </form>
    
</body>
</html>

app/templates/edit_table.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Редактирование стола</title>
    <style>
        body { font-family: Arial; padding: 20px; }
        label { display: block; margin-top: 10px; }
        input, textarea { width: 100%; padding: 6px; }
        button { margin-top: 15px; padding: 10px 20px; }
        img { max-width: 300px; max-height: 300px; margin-top: 10px; }
    </style>
</head>
<body>
    <h1>Редактировать стол: {{ table.name }}</h1>
    <form method="POST" enctype="multipart/form-data">
        <label for="name">Название:</label>
        <input type="text" name="name" value="{{ table.name }}" required><br>

        <label for="description">Описание:</label>
        <textarea name="description">{{ table.description }}</textarea><br>

        <label for="capacity">Вместимость:</label>
        <input type="number" name="capacity" value="{{ table.capacity }}" min="1" required><br>

        <label for="deposit">Депозит:</label>
        <input type="number" step="0.01" name="deposit" value="{{ table.deposit }}"><br>

        <label for="photo">Загрузить фотографию:</label>
        <input type="file" name="photo"><br>

        {% if table.photo %}
            <div>
                <p>Текущая фотография:</p>
                <img src="{{ url_for('static', filename=table.photo.replace('app/static/', '')) }}" alt="Фото стола" style="max-width: 300px; max-height: 300px;">
            </div>
        {% endif %}

        <button type="submit">Сохранить изменения</button>
    </form>
</body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <link rel="icon" href="../static/image/favicon.svg" type="image/svg+xml">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/style/login.css">
    <title>Вход в панель администратора</title>
</head>
<body>
    <div class="main-container">
        <header>
            {% include 'image/favicon.svg' %}
            <h1>BeerFactory Reservations Admin</h1>
        </header>
        <div class="login-area">
            <div class="post-container">
                <h2>Вход</h2>
                <form method="POST">
                    <div class="form-group">
                        <label for="login">Логин</label>
                        <input type="text" id="login" name="login" required value="{{ login_value }}">
                    </div>
                    <div class="form-group">
                        <label for="password">Пароль</label>
                        <input type="password" id="password" name="password" required>
                    </div>
                    <button type="submit">Войти</button>
                </form>
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        <ul class="flashes">
                            {% for category, message in messages %}
                                <li class="{{ category }}">{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                {% endwith %}
            </div>
        </div>
    </div>
</body>
</html>

app/templates/panel.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <link rel="icon" href="../../static/image/favicon.svg" type="image/svg+xml">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../static/style/panel.css">
    <title>Панель администратора</title>
</head>
<body>
    <div class="main-container">
        <header>
            <a href="/brewmaster-secret/panel/">
                {% include 'image/favicon.svg' %}
                <h1>BeerFactory Reservations Admin</h1>
            </a>
        </header>
        <div class="link-area">
            <div class="link-container">
                <a href="/brewmaster-secret/reservations/">Брони</a>
                <a href="/brewmaster-secret/staff/">Сотрудники</a>
                <a href="/brewmaster-secret/uploading/">Выгрузить</a>
                <a href="/brewmaster-secret/logout">Выйти</a>
            </div>
        </div>
    </div>
</body>
</html>

app/templates/reservation_thankyou.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <link rel="icon" href="../static/image/favicon.svg" type="image/svg+xml">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/style/reservation_thankyou.css">
    <title>Спасибо за бронь!</title>
</head>
<body>
    <div class="main-container">
        <header>
            <a href="/">
                {% include 'image/favicon.svg' %}
                <h1>BeerFactory Reservations</h1>
            </a>
        </header>
        <div class="thankyou-contaner">
            <div class="thankyou-heder">
                <h2>Спасибо {{ name }}!</h2>
                <h2>Стол №{{ table_name }} забронирован!</h2>
            </div>

            <div class="thankyou-body">
                <div class="thankyou-data" >
                    <p class="thankyou-lable">Адрес</p>
                    <p>BeerFactory, Красный проспект 22</p>
                </div>
                <div class="thankyou-data">
                    <p class="thankyou-lable">Дата </p>
                    <p>{{ date }}</p>
                </div>
                <div class="thankyou-data">
                    <p class="thankyou-lable">Время</p>
                    <p>с {{ start_time }} до {{ end_time }}</p>
                </div>
                <div class="thankyou-data">
                    <p class="thankyou-lable">Гостей</p>
                    <p>{{ num_people }} чел.</p>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

app/templates/reservations.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <link rel="icon" href="../../static/image/favicon.svg" type="image/svg+xml">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../static/style/reservations.css">
    <script src="../../static/script/reservations.js" defer></script>
    <title>Настройки броней</title>
</head>
<body>
    <div class="main-container">
        <header>
            <a href="/brewmaster-secret/panel/">
                {% include 'image/favicon.svg' %}
                <h1>BeerFactory Reservations Admin</h1>
            </a>
            <div>
                <a class="logout" href="/brewmaster-secret/logout">Выйти</a>
            </div>
        </header>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <div class="flash-messages">
                    {% for category, message in messages %}
                        <div class="flash {{ category }}">
                            <p>{{ message }}</p>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        {% endwith %}
        <div class="filter-area">
            <div class="filter-header">
                <h2>Настройки отображения</h2>
            </div>
            <form method="GET" class="filter-data">
                <label for="filter-date">Дата</label>
                <input type="date" id="filter-date" name="filter_date">
            
                <div>
                    <label for="start-time">Время с</label>
                    <select name="start_time" id="start-time">
                        <option value="">-- не выбрано --</option>
                        {% for hour in range(0, 24) %}
                            {% set time_str = "{:02d}:00".format(hour) %}
                            <option value="{{ time_str }}">{{ time_str }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div>
                    <label for="end-time">до</label>
                    <select name="end_time" id="end-time">
                        <option value="">-- не выбрано --</option>
                        {% for hour in range(0, 24) %}
                            {% set time_str = "{:02d}:00".format(hour) %}
                            <option value="{{ time_str }}">{{ time_str }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="search-block">
                    <label for="search-text">Поиск</label>
                    <input type="text" id="search-text" name="search_query" placeholder="Введите текст...">
                </div>
                <div class="filter-buttons">
                    <button type="button" id="clear-filters-btn">Очистить</button>
                </div>
            </form>
        </div>
        <div class="reservation-area">
            <div class="reservation-header">
                <p>Список броней</p>
                <button id="open-reservation-modal-btn">Добавить</button>
            </div>
            <div class="reservation-table-wrapper">
                <table class="reservation-table-header">
                    <colgroup>
                        <col style="width: 20%;">
                        <col style="width: 15%;">
                        <col style="width: 20%;">
                        <col style="width: 20%;">
                        <col style="width: 10%;">
                        <col style="width: 15%;">
                      </colgroup>
                    <thead>
                        <tr>
                            <th>Имя</th>
                            <th>Статус</th>
                            <th>Дата</th>
                            <th>Время</th>
                            <th>Чел</th>
                            <th>Стол</th>
                        </tr>
                    </thead>
                </table>
                <div class="reservation-data-scroll">
                    <table class="reservation-body">
                        <colgroup>
                            <col style="width: 20%;">
                            <col style="width: 15%;">
                            <col style="width: 20%;">
                            <col style="width: 20%;">
                            <col style="width: 10%;">
                            <col style="width: 15%;">
                        </colgroup>
                        <tbody>
                            {% for reservation in reservations %}
                            <tr class="clickable-row" data-id="{{ reservation.id }}">
                                <td>{{ reservation.name }}</td>
                                <td>{{ reservation.status.name }}</td>
                                <td>{{ reservation.date.strftime('%d.%m.%Y') }}</td>
                                <td>{{ reservation.start_time.strftime('%H:%M') }}–{{ reservation.end_time.strftime('%H:%M') }}</td>
                                <td>{{ reservation.num_people }}</td>
                                <td>{{ reservation.table.name }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>


        <div id="reservation-modal-overlay" class="modal-overlay">
            <div class="modal-content">
                <div class="modal-header">
                    <h2>Добавить бронь</h2>
                    <button type="button" id="close-reservation-modal-btn" class="close-btn">&times;</button>
                </div>
                <form method="POST" action="{{ url_for('main.add_reservations') }}">
                    <label for="name">Имя</label>
                    <input type="text" name="name" required>
        
                    <label for="date">Дата</label>
                    <input type="date" name="date" required>
        
                    <label for="time_from">Время с</label>
                    <input type="time" name="time_from" required>
        
                    <label for="time_to">Время до</label>
                    <input type="time" name="time_to" required>
        
                    <label for="table">Стол</label>
                    <input type="text" name="table" required>
        
                    <label for="people_count">Количество человек</label>
                    <input type="number" name="people_count" required min="1">
        
                    <label for="phone">Телефон</label>
                    <input type="text" name="phone">
        
                    <label for="email">Почта</label>
                    <input type="email" name="email">
        
                    <label for="notes">Особые пожелания</label>
                    <input type="text" name="notes"></input>
        
                    <div class="modal-content-button">
                        <button type="submit">Добавить</button>
                    </div>
                </form>
            </div>
        </div>
        <div id="reservation-modal-overlay-edit" class="modal-overlay">
            <div class="modal-content">
                <div class="modal-header">
                    <h2>Редактировать бронь</h2>
                    <button type="button" id="close-reservation-modal-btn-edit" class="close-btn">&times;</button>
                </div>
                <form id="reservation-edit-form" method="POST" action="{{ url_for('main.update_reservation') }}">
                    <input type="hidden" name="reservation_id" id="reservation-id">
        
                    <label for="name">Имя</label>
                    <input type="text" name="name_edit" id="reservation-name" required>
        
                    <label for="date">Дата</label>
                    <input type="date" name="date_edit" id="reservation-date" required>
        
                    <label for="time_from">Время с</label>
                    <input type="time" name="time_from_edit" id="reservation-start-time" required>
        
                    <label for="time_to">Время до</label>
                    <input type="time" name="time_to_edit" id="reservation-end-time" required>
        
                    <label for="table">Стол</label>
                    <input type="text" name="table_edit" id="reservation-table" required>
        
                    <label for="people_count">Количество человек</label>
                    <input type="number" name="people_count_edit" id="reservation-num-people" required min="1">
        
                    <label for="phone">Телефон</label>
                    <input type="text" name="phone_edit" id="reservation-phone">
        
                    <label for="email">Почта</label>
                    <input type="email" name="email_edit" id="reservation-email">
        
                    <label for="notes">Особые пожелания</label>
                    <input type="text" name="notes_edit" id="reservation-special-requests">
        
                    <label for="status_edit">Статус</label>
                    <select name="status_edit" id="reservation-status" required></select>
        
                    <div class="info-block">
                        <p id="reservation-created-at"></p>
                        <p id="reservation-responsible"></p>
                    </div>
        
                    <div class="modal-content-button">
                        <button type="submit">Сохранить</button>
                        <button type="button" id="remove-reservation-btn">Удалить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

app/templates/tables_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Список столов</title>
    <style>
        body { font-family: Arial; padding: 20px; }
        .table-item { border: 1px solid #ccc; margin: 10px 0; padding: 10px; border-radius: 8px; }
        .table-item img { max-width: 200px; max-height: 150px; display: block; margin-bottom: 10px; }
    </style>
</head>
<body>
    <h1>Список столов</h1>
    <a href="{{ url_for('main.add_table') }}">➕ Добавить новый стол</a>

    {% for table in tables %}
        <div class="table-item">
            {% if table.photo %}
                <img src="{{ url_for('static', filename=table.photo.replace('app/static/', '')) }}" alt="Фото стола" style="max-width: 300px; max-height: 300px;">
            {% endif %}
            <h2>{{ table.name }}</h2>
            <p><strong>Описание:</strong> {{ table.description }}</p>
            <p><strong>Вместимость:</strong> {{ table.capacity }} человек</p>
            <p><strong>Депозит:</strong> {{ table.deposit }} руб.</p>
            <a href="{{ url_for('main.edit_table', table_id=table.id) }}">✏️ Редактировать</a>
        </div>
    {% endfor %}
</body>
</html>

app/templates/uploading.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <link rel="icon" href="../../static/image/favicon.svg" type="image/svg+xml">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../static/style/uploading.css">
    <script src="../../static/script/uploading.js" defer></script>
    <title>Выгрузка броней</title>
</head>
<body>
    <div class="main-container">
        <header>
            <a href="/brewmaster-secret/panel/">
                {% include 'image/favicon.svg' %}
                <h1>BeerFactory Reservations Admin</h1>
            </a>
        </header>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <div class="flash-messages">
                    {% for category, message in messages %}
                        <div class="flash {{ category }}">
                            <p>{{ message }}</p>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        {% endwith %}
        <div class="uploading-area">
            <h2>Выгрузить брони</h2>
            <form action="{{ url_for('main.get_reservations') }}" method="GET">
                <div>
                    <label for="start-date">С</label>
                    <input type="date" id="start-date" name="start_date" required>
                </div>
                <div>
                    <label for="end-date">По</label>
                    <input type="date" id="end-date" name="end_date" required>
                </div>
                <button type="submit">Выгрузить</button>
            </form>
        </div>
    </div>
</body>
</html>    